# Nome do site
#name: Garcez Filho | Advocacia & Consultoria Jurídica

# Descrição do site
#description: Este é o meu site pessoal

# Configurações de URL
#
# Comentar os campos baseurl e url quando estiver rodando o
# servidor do jekyll localmente
#
baseurl: "https://blog.garcezfilho.com.br"
url: "https://blog.garcezfilho.com.br"

# Encoding padrão (opcional, mas recomendável)
encoding: UTF-8

# Configurações de Markdown
markdown: kramdown
highlighter: rouge

# Definindo que os 
locale: pt-BR
language: pt-BR
date_format: "pt-BR"

# Configurações de Data
timezone: America/Sao_Paulo

# Configurações de Página Inicial
#paginate: 0
#paginate_path: "/página/:num"

# Criando um permalink padrão para os Posts
permalink: /posts/:categories/:year/:month/:day/:title/

# Configurações de Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-algolia

algolia:
  application_id: $ALGOLIA_APP_ID
  api_key: $ALGOLIA_API_KEY
  index_name: $ALGOLIA_INDEX_NAME

# Configurações de Pastas
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - .bundle/
  - .jekyll-cache/
  - .sass-cache/
  - .jekyll-metadata

# Configurações de Build
#future: true
#limit_posts: 100

# Configurações de Saída
lsi: false
strip_index_file: false
